#!/bin/sh

FLAGS="-Cftrx.on=true\
       -Cftrx.keep-ft=true\
       -Cast.inline-ranges=true\
       -Cast.keep-inline-ranges=true"

SRC_FILE=$1
ERR_FILE=Errors_${SRC_FILE%%.pml}

../pmlc $FLAGS $SRC_FILE 2>&1 | tee $ERR_FILE
