#!/bin/sh

PML_FLAGS="-Cftrx.keep-ft=true -Cftrx.on=true -Ccps.flatten=false -Cast.keep-inline-ranges=true"
CP_FLAG="-chunking-policy ETS 1024"

echo "NOTE: running tests using the following chunking policy: $CP_FLAG"
echo ""

for PML_PROGRAM in *.pml ; do
  echo "compiling $PML_PROGRAM"
  # EXEC=${PML_PROGRAM%%.pml}
  EXEC=a.out
  # CMD="../pmlc $PML_FLAGS -o $EXEC $PML_PROGRAM 2>&1 | tee ErrorTranscript_$EXEC"
  CMD="./Build $PML_PROGRAM"
  echo $CMD && $CMD
  echo "running $PML_PROGRAM"
  ./$EXEC $CP_FLAG
  echo "finished with $PML_PROGRAM"
  rm $EXEC
  echo ""
done

echo "Altogether done. Run ./Cleanup to remove temporary files."


